# SPDX-License-Identifier: GPL-2.0
rt2x00lib-y				+= rt2x00dev.o
rt2x00lib-y				+= rt2x00mac.o
rt2x00lib-y				+= rt2x00config.o
rt2x00lib-y				+= rt2x00queue.o
rt2x00lib-y				+= rt2x00link.o
rt2x00lib-y				+= rt2x00debug.o
rt2x00lib-y				+= rt2x00crypto.o
rt2x00lib-y				+= rt2x00firmware.o
rt2x00lib-y				+= rt2x00leds.o

obj-m		+= rt2x00lib.o
obj-m		+= rt2x00usb.o
obj-m		+= rt2800lib.o
obj-m		+= rt2800usb.o
